### ISSUE TITLE
adding an upgrade[Crash]: 

### ISSUE THREAD

**Issue by jayssuburbia** [MattiDragon/ExtendedDrawers#123]
### Description of the issue

I try to add an upgrade to a drawer and I crash

### Reproduction steps

I shift click the upgrade on the front of the drawer then the game crashes

### Mod version

3.0.2

### Operating System

windows 11

### Minecraft version

1.21

### Other mods

Fabric API 0.100.7 + 1.21

### Server

Happens

### Client

Not tested

### Logs

-1

### Crash Report

-1

**Comment by MattiDragon** [comment]
Install indium. If you only have sodium and not indium extended drawers won't work

**Comment by jayssuburbia** [comment]
Thank you worked. Is that something new?  I didn't need that before.

**Comment by MattiDragon** [comment]
It has always been like that. You might have uninstalled indium as it wasn't available on latest for some time. Could also be that you never upgraded any drawers, because only upgrades and modifiers breaks without indium. There was also a popup before about installing indium, but the mod adding that hasn't updated, so it's no longer bundled
