### ISSUE TITLE
[Feature]: feedback on appearance

### ISSUE THREAD

**Issue by Abalieno** [MattiDragon/ExtendedDrawers#59]
### Description of the feature

As already said:

https://i.imgur.com/wpmR9kF.png

Since textures can be locally edited, that part is just a matter of preference.

Here are some objective problems though:

- ~~the lock on the compacting drawer could be moved to the side so not to disturb the icon (or, if you want symmetry, right in the center of the drawer, since it affects all 3 slots, but making sure it doesn't overlap with the item count of the upper drawer)~~ Now renders as a small icon
- for some reason, bronze doesn't detect the bronze nugget. This is Modern Industrialization, but I couldn't detect and discrepancy between bronze and steel, no different tags either. I can't understand what kind of logic it uses to detect the three items, but something is behaving weirdly.
- ~~have you noticed the weird shading? Look at redstone. The dusts are shaded, but the block is not. If you look these on REI/EMI you can see they share the same brightness, but not here. The way items and block are rendered should be unified.~~ Fixed in 1.4.1
- ~~It would also be nice to be able to customize text separately: both in size (since it's now tied to the icon size) and placement so that I could align it better in the frame. And since alignment depends on the size, adding options to both would be useful, if possible.~~ Fixed in 1.4.1

### How does it make the mod better?

More consistent, improved appearance.

**Comment by Abalieno** [comment]
Oh, and since the text size on the single drawer looks good to me, if you add an option to scale the text, give it at least 2 options. One for the single drawer and another that can be used for all the smaller ones.

Or I'd end up with a situation that I need to make the small ones bigger, but the single one gets huge and it doesn't look very good.

**Comment by MattiDragon** [comment]
Most of these changes will probably only get implemented in the 1.20 version as I plan on reworking the config. The properties system currently in use just isn't powerful enough. 

I do plan on looking into what's up with shading on blocks. The reason items appear dark is because they are rendered with the light in the world instead of as unlit like in the inventory. I suspect this won't be an easy fix. 

On the bronze: the compacting drawer uses crafting recipes to check which items can compact. You can also add overrides as explained in the description. The only way I see it not working is if the recipes end up converting to bronze from some other mod.

**Comment by MattiDragon** [comment]
Would you be interested in testing some changes I made? I added some options and changed some defaults. Unzip the attached file and use the mod jar inside. Had to use a zip as github doesn't allow jar uploads.

Btw, you should join the discord so that we can discuss these changes better.

[ExtendedDrawers-1.4.1-dev.128+mc.1.19.4.zip](https://github.com/MattiDragon/ExtendedDrawers/files/11582204/ExtendedDrawers-1.4.1-dev.128%2Bmc.1.19.4.zip)

**Comment by MattiDragon** [comment]
Fixed everything but the bronze issue. It's probably either because crafting the nuggets back into ingots gives you the wrong type of bronze ingot.
