### ISSUE TITLE
[Bug]: guide book doesn't use proper ID

### ISSUE THREAD

**Issue by 800020h** [MattiDragon/ExtendedDrawers#65]
### Description of the issue

the guide book is IDed as `patchouli:guide_book`
it should use a unique ID so conflicts can't happen

### Reproduction steps

take a look in game with advanced tooltips on

### Mod version

1.4.1+mc.1.19.2

### Operating System

n/a

### Minecraft version

1.19.2

### Other mods

patchouli 1.19.2-77-FABRIC

and other mods that aren't relevant

### Server

Not tested

### Client

Not tested

### Logs

n/a

### Extra Context

![image](https://github.com/MattiDragon/ExtendedDrawers/assets/100995970/901bfdfb-d23b-4ef0-8e8c-6688e08c59e8)

**Comment by MattiDragon** [comment]
This is just how patchouli works, the actual book id is stored in the nbt. There won't be any conflicts because each book has a unique id. 

It's possible that I'm using the wrong api and that I could have my own item id, but I know for sure that this works just fine. If this causes actual issues with another mod then I can look into it more.

**Comment by 800020h** [comment]
spectrum, botania, ad astra, and others all have unique IDs for their (patchouli) guide books

**Comment by MattiDragon** [comment]
I'll look into it, but the current one should still work just fine
