### ISSUE TITLE
[Bug]: Locked Empty Drawers do not prevent items from entering that slot through an AE2 terminal.

### ISSUE THREAD

**Issue by PlayfulPiano** [MattiDragon/ExtendedDrawers#78]
### Description of the issue

I'm specifically referring to slots like this:
![image](https://github.com/MattiDragon/ExtendedDrawers/assets/3158887/fa4c18d2-986f-40b3-b222-4ce54d9812ec)

I thought I could set a slot like this so putting new items within my ME system wouldn't fill these slots (so later on I can specify specific items that take a lot of storage), but anytime a new item not previously in my ME system is put into the system through a terminal, it goes into the above slot when at equal priority between the AE2 storage bus (set to the drawer access point) and the AE2 ME drive.

### Reproduction steps

1. Setup an ME system with a storage bus connected to a drawer access point (that is also connected to any drawer).
2. Lock the empty drawer slots.
3. Put items not already in the ME system into the system through an ME terminal.

### Mod version

v1.3.7

### Operating System

Windows 10

### Minecraft version

1.18.2

### Other mods

Applied Energistics 2 v11.7.6
Fabric API v0.76.0

### Server

Not tested

### Client

Happens

### Logs

https://paste.ee/p/1elaB

**Comment by MattiDragon** [comment]
I don't support 1.18 at all for any of my mods. This has most likely been fixed in a later version. If you can reporoduce on 1.20(.2) then you can reopen this issue. If you can reproduce on 1.19.2 or 1.19.4 then I might consider fixing. I haven't touched the 1.18 for a long time and don't plan to in the future. If you make a pull request I might accept it.

Edit: confimed to be an old bug: #53. It was fixed in 1.3.10 which only supported 1.19 and up.
