### ISSUE TITLE
[Feature]: More control over how much items you take

### ISSUE THREAD

**Issue by BenjaTK** [MattiDragon/ExtendedDrawers#84]
### Description of the feature

I think it could be interesting to add more "modifiers" to take different amount of items. The idea I had was:
Shift: 64 items
Shift + Alt: 32
Ctrl: 16
Ctrl + Alt: 8

### How does it make the mod better?

I know this could make it a bit overcomplicated so I understand if you don't add it, but I think it would be a good QOL feature to have to reduce click spamming or taking a stack and going to your inventory to divide it.

**Comment by MattiDragon** [comment]
This would quickly become complicated because the server, which handles giving you items, doesn't know about what keys you are pressing. The client sends the sneaking status that I used currently. I'd need to implement keybinds and syncing. Consider hooking up your drawers to a digital storage mod if you want easy access.
